sudo: false
language: bash
os: linux
dist: trusty

matrix:
  include:
    - env:
      - BUILD_TYPE=build
    - env:
      - BUILD_TYPE=build_esp32

install:

script:
  - $TRAVIS_BUILD_DIR/tests/common.sh

deploy:

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
